temp: utils: Action.java build fix
 * frameworks/base/core/java/com/android/internal/util/candy/Action.java:258: error: method dismissKeyguard in interface IWindowManager cannot be applied to given types;
            WindowManagerGlobal.getWindowManagerService().dismissKeyguard();
                                                       ^
  required: IKeyguardDismissCallback
  found: no arguments
  reason: actual and formal argument lists differ in length

  * need to fix that when time permits, or someone should

Change-Id: Ifd10fd0fcadc5d5d86baa50808205b07ae2e6411